# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestCodelesssample():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_codelesssample(self):
        # Test name: codeless_sample
        # Step # | name | target | value
        # 1 | open | /en-gb/ |
        self.driver.get("http://selenium1py.pythonanywhere.com/en-gb/")
        # 2 | setWindowSize | 1536x824 |
        self.driver.set_window_size(1536, 824)
        # 3 | click | id=login_link |
        self.driver.find_element(By.ID, "login_link").click()
        # 4 | click | id=id_registration-email |
        self.driver.find_element(By.ID, "id_registration-email").click()
        # 5 | type | id=id_registration-email | adress_2@email.com
        self.driver.find_element(By.ID, "id_registration-email").send_keys("adress_2@email.com")
        # 6 | type | id=id_registration-password1 | 123456789Ven
        self.driver.find_element(By.ID, "id_registration-password1").send_keys("123456789Ven")
        # 7 | type | id=id_registration-password2 | 123456789Ven
        self.driver.find_element(By.ID, "id_registration-password2").send_keys("123456789Ven")
        # 8 | click | name=registration_submit |
        self.driver.find_element(By.NAME, "registration_submit").click()
        # 9 | close |  |
        self.driver.close()

